require: rubocop-rspec

Style/ClassAndModuleChildren:
  EnforcedStyle: nested

SpaceAroundEqualsInParameterDefault:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/RescueStandardError:
  EnforcedStyle: implicit

Style/RescueModifier:
  Enabled: false

Style/NumericPredicate:
  Enabled: false

Style/TrailingCommaInHashLiteral:
  Enabled: false

Style/TrailingCommaInArrayLiteral:
  Enabled: false

Style/Lambda:
  EnforcedStyle: literal

Layout/SpaceInLambdaLiteral:
  EnforcedStyle: require_space

Layout/EmptyLineAfterGuardClause:
  Enabled: false

Metrics/LineLength:
  Max: 100

Metrics/MethodLength:
  Max: 15

Naming/FileName:
  Exclude:
    - 'Gemfile'

AllCops:
  TargetRubyVersion: 2.5.1
  Exclude:
    - db/schema.rb
    - db/migrate/*.rb
    - bin/*
    - node_modules/*
    - lib/**/*.rake
    - config/puma.rb
    - config/environments/*.rb
    - Rakefile
    - config.ru
